import type { Metadata } from "next";
import localFont from "next/font/local";
import SessionWrapper from "@/components/SessionWrapper";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Toaster } from 'react-hot-toast';
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import CSS
import { Suspense } from "react";
config.autoAddCss = false; // Nonaktifkan auto-adding CSS


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Insite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <SessionWrapper>
      <html lang="en">
      <head>
          <link rel="icon" href="img/logo.png" />
          <link
          href="https://fonts.googleapis.com/css2?family=Alex+Brush&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Suspense>
          {children}
          </Suspense>
      <Toaster/>
      </body>
    </html> 
  </SessionWrapper>
  );
}
